import { StyleSheet } from 'react-native';

export const deviceConfigStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f9fafb',
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 16,
        fontSize: 14,
        color: '#6b7280',
    },
    header: {
        backgroundColor: '#2563eb',
        paddingHorizontal: 20,
        paddingBottom: 16,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#ffffff',
        marginBottom: 2,
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#dbeafe',
        marginBottom: 14,
    },
    stepperContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 4,
    },
    stepComplete: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#10b981',
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepActive: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#ffffff',
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepActiveText: {
        color: '#2563eb',
        fontSize: 12,
        fontWeight: 'bold',
    },
    stepLine: {
        flex: 1,
        height: 3,
        backgroundColor: '#10b981',
        marginHorizontal: 8,
        maxWidth: 80,
        borderRadius: 2,
    },
    stepInactive: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepInactiveText: {
        color: 'rgba(255, 255, 255, 0.7)',
        fontSize: 12,
        fontWeight: 'bold',
    },
    stepLineInactive: {
        flex: 1,
        height: 3,
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        marginHorizontal: 8,
        maxWidth: 80,
        borderRadius: 2,
    },
    contentArea: {
        flex: 1,
        padding: 14,
    },
    retryBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fef3c7',
        borderRadius: 10,
        padding: 10,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#fde68a',
    },
    retryText: {
        flex: 1,
        fontSize: 12,
        color: '#92400e',
        marginLeft: 8,
        fontWeight: '600',
    },
    empresaCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#eff6ff',
        borderRadius: 12,
        padding: 12,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#dbeafe',
    },
    empresaInfo: {
        flex: 1,
        marginLeft: 10,
    },
    empresaLabel: {
        fontSize: 10,
        color: '#6b7280',
        marginBottom: 1,
    },
    empresaNombre: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1e40af',
    },
    formCard: {
        backgroundColor: '#fff',
        borderRadius: 14,
        padding: 12,
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#f0f0f4',
    },
    fieldContainer: {
        marginBottom: 10,
    },
    label: {
        fontSize: 11,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 4,
    },
    required: {
        color: '#ef4444',
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f9fafb',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        paddingHorizontal: 10,
    },
    inputWrapperReadonly: {
        backgroundColor: '#f3f4f6',
        borderColor: '#d1d5db',
    },
    inputWrapperValid: {
        borderColor: '#10b981',
        borderWidth: 2,
        backgroundColor: '#f0fdf4',
    },
    inputWrapperInvalid: {
        borderColor: '#ef4444',
        borderWidth: 2,
        backgroundColor: '#fef2f2',
    },
    inputIcon: {
        marginRight: 6,
    },
    input: {
        flex: 1,
        height: 38,
        fontSize: 13,
        color: '#374151',
    },
    inputReadonly: {
        color: '#6b7280',
    },
    helpText: {
        fontSize: 10,
        color: '#6b7280',
        marginTop: 3,
        marginLeft: 2,
    },
    validatingText: {
        fontSize: 11,
        color: '#2563eb',
        marginTop: 4,
        marginLeft: 2,
    },
    validationMessage: {
        fontSize: 11,
        marginTop: 4,
        marginLeft: 2,
    },
    validMessage: {
        color: '#10b981',
    },
    invalidMessage: {
        color: '#ef4444',
    },
    deviceInfoRow: {
        flexDirection: 'row',
        gap: 8,
        flexWrap: 'wrap',
    },
    deviceInfoChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#eff6ff',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
        gap: 5,
        borderWidth: 1,
        borderColor: '#dbeafe',
    },
    deviceInfoChipText: {
        fontSize: 11,
        color: '#1e40af',
        fontWeight: '500',
    },
    footer: {
        backgroundColor: '#fff',
        paddingHorizontal: 16,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
    },
    warningRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fef3c7',
        borderRadius: 10,
        padding: 10,
        marginBottom: 10,
        gap: 8,
        borderWidth: 1,
        borderColor: '#fde68a',
    },
    warningText: {
        flex: 1,
        fontSize: 11,
        color: '#92400e',
        lineHeight: 15,
    },
    buttonRow: {
        flexDirection: 'row',
        gap: 12,
    },
    backButton: {
        flex: 1,
        backgroundColor: '#fff',
        borderWidth: 1.5,
        borderColor: '#e5e7eb',
        borderRadius: 14,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    backButtonText: {
        color: '#6b7280',
        fontSize: 14,
        fontWeight: '600',
    },
    nextButton: {
        flex: 2,
        backgroundColor: '#2563eb',
        borderRadius: 14,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        shadowColor: '#2563eb',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 4,
    },
    nextButtonDisabled: {
        backgroundColor: '#9ca3af',
        shadowOpacity: 0,
        elevation: 0,
    },
    nextButtonText: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: 'bold',
        marginRight: 6,
    },
    macHelpButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 8,
        paddingVertical: 6,
        paddingHorizontal: 8,
        backgroundColor: '#eff6ff',
        alignSelf: 'flex-start',
        borderRadius: 8,
    },
    macHelpButtonText: {
        fontSize: 12,
        color: '#4f46e5',
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 16,
        width: '100%',
        maxWidth: 400,
        padding: 20,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalHeaderIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#eff6ff',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1f2937',
        flex: 1,
    },
    closeModalButton: {
        padding: 4,
    },
    modalScroll: {
        maxHeight: 300,
    },
    stepItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        gap: 12,
    },
    stepText: {
        flex: 1,
        fontSize: 14,
        color: '#4b5563',
        lineHeight: 20,
    },
    macFormatNote: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ecfdf5',
        padding: 12,
        borderRadius: 8,
        marginTop: 8,
        marginBottom: 20,
        gap: 8,
        borderWidth: 1,
        borderColor: '#a7f3d0',
    },
    macFormatText: {
        fontSize: 13,
        color: '#065f46',
        fontWeight: '500',
        flex: 1,
    },
    modalActions: {
        gap: 10,
        marginTop: 10,
    },
    modalPrimaryButton: {
        backgroundColor: '#2563eb',
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
    },
    modalPrimaryButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: 'bold',
    },
    modalSecondaryButton: {
        backgroundColor: '#f3f4f6',
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
    },
    modalSecondaryButtonText: {
        color: '#4b5563',
        fontSize: 15,
        fontWeight: '700',
    },
});
