import { StyleSheet } from 'react-native';

export const registerStyles = StyleSheet.create({
    container: {
        backgroundColor: '#fff',
        marginHorizontal: 20,
        marginTop: 12,
        borderRadius: 16,
        padding: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    statusContainer: {
        alignItems: 'center',
        marginBottom: 8,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 20,
        gap: 4,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '600',
    },
    content: {
        gap: 8,
    },
    timeContainer: {
        alignItems: 'center',
        paddingVertical: 6,
    },
    timeLabel: {
        fontSize: 11,
        color: '#9ca3af',
        marginBottom: 2,
    },
    timeValue: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1f2937',
        letterSpacing: -1,
    },
    statusIndicators: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 12,
        paddingVertical: 4,
    },
    indicator: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
    },
    indicatorText: {
        fontSize: 11,
        fontWeight: '500',
    },
    locationInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        paddingVertical: 6,
        backgroundColor: '#f9fafb',
        borderRadius: 8,
    },
    locationText: {
        fontSize: 12,
        color: '#6b7280',
        fontWeight: '500',
    },
    registerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 12,
        gap: 6,
        marginTop: 2,
    },
    registerButtonDisabled: {
        opacity: 0.5,
    },
    registerButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '600',
    },
    lastRegisterContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        paddingTop: 6,
        borderTopWidth: 1,
        borderTopColor: '#f3f4f6',
        marginTop: 2,
    },
    lastRegisterIcon: {
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: '#f3f4f6',
        alignItems: 'center',
        justifyContent: 'center',
    },
    lastRegisterText: {
        fontSize: 11,
        color: '#9ca3af',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '70%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
    },
    modalCloseButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#f3f4f6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    departamentosList: {
        padding: 16,
    },
    departamentoItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 14,
        backgroundColor: '#f9fafb',
        borderRadius: 12,
        marginBottom: 10,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    departamentoItemActivo: {
        backgroundColor: '#ecfdf5',
        borderColor: '#10b981',
    },
    departamentoInfo: {
        flex: 1,
        gap: 6,
    },
    departamentoHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    departamentoNombre: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1f2937',
        flex: 1,
    },
    departamentoNombreActivo: {
        color: '#059669',
    },
    departamentoBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingLeft: 28,
    },
    departamentoBadgeText: {
        fontSize: 12,
        color: '#10b981',
        fontWeight: '500',
    },
    modalFooter: {
        padding: 16,
        borderTopWidth: 1,
        borderTopColor: '#f3f4f6',
    },
    infoBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        padding: 12,
        backgroundColor: '#eff6ff',
        borderRadius: 8,
    },
    infoBoxText: {
        flex: 1,
        fontSize: 12,
        color: '#3b82f6',
        lineHeight: 16,
    },
    viewMapButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: '#eff6ff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#dbeafe',
    },
    viewMapText: {
        fontSize: 13,
        color: '#3b82f6',
        fontWeight: '600',
    },
    authModalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingTop: 32,
        paddingBottom: 24,
        paddingHorizontal: 24,
    },
    authHeader: {
        alignItems: 'center',
        marginBottom: 24,
    },
    authTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#1f2937',
        marginTop: 12,
    },
    authSubtitle: {
        fontSize: 14,
        color: '#6b7280',
        marginTop: 4,
    },
    authMethodsContainer: {
        gap: 12,
        marginBottom: 20,
    },
    authMethodCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#f9fafb',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    authMethodIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#eff6ff',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    authMethodName: {
        flex: 1,
        fontSize: 16,
        fontWeight: '600',
        color: '#1f2937',
    },
    authCancelButton: {
        paddingVertical: 14,
        alignItems: 'center',
    },
    authCancelText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#6b7280',
    },
});

export const registerStylesDark = StyleSheet.create({
    container: {
        backgroundColor: '#1f2937',
        marginHorizontal: 20,
        marginTop: 12,
        borderRadius: 16,
        padding: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    statusContainer: {
        alignItems: 'center',
        marginBottom: 8,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 20,
        gap: 4,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '600',
    },
    content: {
        gap: 8,
    },
    timeContainer: {
        alignItems: 'center',
        paddingVertical: 6,
    },
    timeLabel: {
        fontSize: 11,
        color: '#9ca3af',
        marginBottom: 2,
    },
    timeValue: {
        fontSize: 24,
        fontWeight: '700',
        color: '#f9fafb',
        letterSpacing: -1,
    },
    statusIndicators: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 12,
        paddingVertical: 4,
    },
    indicator: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
    },
    indicatorText: {
        fontSize: 11,
        fontWeight: '500',
    },
    locationInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        paddingVertical: 6,
        backgroundColor: '#374151',
        borderRadius: 8,
    },
    locationText: {
        fontSize: 12,
        color: '#9ca3af',
        fontWeight: '500',
    },
    registerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 12,
        gap: 6,
        marginTop: 2,
    },
    registerButtonDisabled: {
        opacity: 0.5,
    },
    registerButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '600',
    },
    lastRegisterContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        paddingTop: 6,
        borderTopWidth: 1,
        borderTopColor: '#374151',
        marginTop: 2,
    },
    lastRegisterIcon: {
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: '#374151',
        alignItems: 'center',
        justifyContent: 'center',
    },
    lastRegisterText: {
        fontSize: 11,
        color: '#9ca3af',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#1f2937',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '70%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#374151',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#f9fafb',
    },
    modalCloseButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#374151',
        justifyContent: 'center',
        alignItems: 'center',
    },
    departamentosList: {
        padding: 16,
    },
    departamentoItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 14,
        backgroundColor: '#374151',
        borderRadius: 12,
        marginBottom: 10,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    departamentoItemActivo: {
        backgroundColor: '#065f46',
        borderColor: '#10b981',
    },
    departamentoInfo: {
        flex: 1,
        gap: 6,
    },
    departamentoHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    departamentoNombre: {
        fontSize: 15,
        fontWeight: '600',
        color: '#f9fafb',
        flex: 1,
    },
    departamentoNombreActivo: {
        color: '#10b981',
    },
    departamentoBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingLeft: 28,
    },
    departamentoBadgeText: {
        fontSize: 12,
        color: '#10b981',
        fontWeight: '500',
    },
    modalFooter: {
        padding: 16,
        borderTopWidth: 1,
        borderTopColor: '#374151',
    },
    infoBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        padding: 12,
        backgroundColor: '#1e3a8a',
        borderRadius: 8,
    },
    infoBoxText: {
        flex: 1,
        fontSize: 12,
        color: '#93c5fd',
        lineHeight: 16,
    },
    viewMapButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: '#1e3a8a',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#1e40af',
    },
    viewMapText: {
        fontSize: 13,
        color: '#93c5fd',
        fontWeight: '600',
    },
    authModalContent: {
        backgroundColor: '#1f2937',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingTop: 32,
        paddingBottom: 24,
        paddingHorizontal: 24,
    },
    authHeader: {
        alignItems: 'center',
        marginBottom: 24,
    },
    authTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#f9fafb',
        marginTop: 12,
    },
    authSubtitle: {
        fontSize: 14,
        color: '#9ca3af',
        marginTop: 4,
    },
    authMethodsContainer: {
        gap: 12,
        marginBottom: 20,
    },
    authMethodCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#374151',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#4b5563',
    },
    authMethodIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#1e3a8a',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    authMethodName: {
        flex: 1,
        fontSize: 16,
        fontWeight: '600',
        color: '#f9fafb',
    },
    authCancelButton: {
        paddingVertical: 14,
        alignItems: 'center',
    },
    authCancelText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#9ca3af',
    },
});
